config/routes.rb
Rails.application.routes.draw do

  resources :relationships
  resources :ribbits
  #get 'sessions/new'

  #get 'sessions/create'

  #get 'sessions/destroy'

  #get 'new/created'

  #get 'new/create'

  #get 'new/destroy'

  resources :sessions

  resources :users

  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'buddies', to: 'users#buddies', as: 'buddies'

  root to: "users#new"
  get 'welcome/index'
  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord


	#attr_accessible :followed_id, :follower_id

	#attr_accessor :followed_id, :follower_id

	belongs_to :follower, class_name: 'User'
	belongs_to :followed, class_name: 'User'

end

app/models/ribbit.rb
class Ribbit < ApplicationRecord
		attr_accessor :content, :user_id

		#default_scope order: "created_at DESC"
		default_scope {order('created_at DESC')}

		belongs_to :user

		validates :content, length: { maximum: 140 }
end

app/models/user.rb
require 'digest/md5'

class User < ApplicationRecord
	#attr_accessor :avatar_url, :bio, :email, :name, :password, :password_confirmation, :username
	has_secure_password

	has_many :ribbits

	has_many :follower_relationships, class_name: 'Relationship', foreign_key: 'followed_id'
	has_many :followed_relationships, class_name: 'Relationship', foreign_key: 'follower_id'

	has_many :followers, through: :follower_relationships
	has_many :followeds, through: :followed_relationships

	def following? user
		self.followeds.include? user 
	end

	def follow user
		Relationship.create follower_id: self.id, followed_id: user.id
	end






before_validation :prep_email
before_save :create_avatar_url


	validates :email, presence: true, uniqueness: true, format:{ with: /\A[\w\.+-]+@([\w]+\.)+[a-zA-Z]+\Z/ }
	validates :username, presence: true, uniqueness: true
	validates :name, presence: true
	#validates :gender, presence: true



	private

	def prep_email
		self.email = self.email.strip.downcase if self.email
	end

	def create_avatar_url
		self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


private

def current_user
	@current_user = User.find(session[:user_id]) if session[:user_id]
end

helper_method :current_user


end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def created
  end

  def destroy
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController




def create
	@relationship = Relationship.create(app_params)
	@relationship.follower = current_user

	flash[:error] = "could not follow this sexy creature" unless @relationship.save
	redirect_to @relationship.followed
end

def destroy
	relationship = Relationship.find(params[:id])
	user = relationship.followed
	relationship.destroy
	redirect_to user
end




private
def app_params
	params.require(:relationship).permit(:follower_id, :followed_id, :follower_relationships, :followed_relationships, :followers, :followeds)
end



end

app/controllers/ribbits_controller.rb
class RibbitsController < ApplicationController
	
def index
	@ribbits = Ribbit.all
	@ribbit = Ribbit.new
end

	def create_params
		params.require(:ribbit).permit(:content, :user_id)
	end

	def create
		if @ribbit = Ribbit.new(create_params)
		@ribbit.user_id = current_user.id
		@ribbit.save


		flash[:success] = "Welcome to Sexy Ribbit! You just ribbited bitch!"
      	redirect_to root_url

      else

		flash[:error] = "Over 140 characters. Get to the point dude!" 
		redirect_to root_url

	end
	end

	

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  #def new
  #end

  def create
  	user = User.find_by_username params[:username]
  	if user and user.authenticate(params[:password])
  		session[:user_id] = user.id     #user.user_id (TUTORIAL MISTAKE)
  		redirect_to root_url, notice: "Logged In!"
  		else
  			flash[:error] = "wrong username orrr password my sexual chocolate"
  			redirect_to root_url
  		end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "Logged Out My Sweet Salted Caramel"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
	if current_user
		redirect_to buddies_path
	else
	@user = User.new
end
end

#changed (params[:user]) to (user_params)

#def create
	#@user = User.new(params[:user])
	#if @user.save
	#	redirect_to @user, notice: "Thank you for sexing it up for Ribbit!"
	#else
	#	render 'new'
	#end

def show
	@user = User.find(params[:id])
	@ribbit = Ribbit.new
	@relationship = Relationship.where(
		follower_id: current_user.id,
		followed_id: @user.id
		).first_or_initialize if current_user
end




def edit
	@user = User.find(params[:id])

	redirect_to @user unless @user == current_user
	#@user = User.find(user_params)
	
end


def update
	@user = User.find(params[:id])
	#@user = User.find(user_params)

	if @user.update_attributes(user_params)
		redirect_to @user, notice: "Sexy Profile Updated!"
	else
		render 'edit'
	end
end

def user_params
	params.require(:user).permit(:relationship, :full_name, :password, :email, :name, :password_confirmation)
end





def allowed_params
	params.require(:user).permit(:relationship, :full_name, :password, :email, :name, :username, :password_confirmation)
end

def create
	@user = User.create(allowed_params)
	if @user.save
		session[:user_id] = @user.id
		redirect_to users_path @user, notice: "This is the second create method"
	else
		render 'new'
	end

	#redirect_to users_path
end

def index
	@users = User.all
	@ribbit = Ribbit.new
end

def buddies
	if current_user
		@ribbit = Ribbit.new
		buddies_ids = current_user.followeds.map(&:id).push(current_user.id)
		#@ribbits = Ribbit.find_all_by_user_id buddies_ids
		@ribbits = Ribbit.where(user_id: buddies_ids)

	else
		redirect_to root_url
	end
	
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/ribbits_helper.rb
module RibbitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Cocksucker</title>
	<link rel="stylesheet/less" href="/style.less" />
	<script src="/less.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>


  	<header>
  		<div class="wrapper">
  			<img src="/gfx/logo.png"/>
  			<span>Sexy Twitter Clone</span>
        <% if current_user %>

        <%= link_to "Buddies Ribbits", buddies_path %>

        <%= link_to "Public Ribbits", ribbits_path %>

        <%= link_to "Public Profiles", users_path %>

        <%= link_to "My Profile", current_user %>

        <%= link_to "Pull Out", logout_path %>

        <% else %>
        <%= form_tag sessions_path do %>
          <%= text_field_tag :username, nil, placeholder: "username" %>
          <%= password_field_tag :password, nil, placeholder: "password" %>
          <%= submit_tag "Poke me baby" %>
        <% end %>
        <% end %>



  		</div>
  		</header>

<div id="content">
	<div class="wrapper">
		<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, class: "flash #{name}" %>
		<% end %>
  			<%= yield %>
  		</div>
  </div>
  <footer>
	  	<div class="wrapper">
	  		Ribbit - A Twitter Clone Tutorial <img src="/gfx/logo-nettuts.png">
	  	</div>
  </footer>


</body>
</html>

app/views/new/create.html.erb
<h1>New#create</h1>
<p>Find me in app/views/new/create.html.erb</p>

app/views/new/created.html.erb
<h1>New#created</h1>
<p>Find me in app/views/new/created.html.erb</p>

app/views/new/destroy.html.erb
<h1>New#destroy</h1>
<p>Find me in app/views/new/destroy.html.erb</p>

app/views/ribbits/_new_form.html.erb
<div class="panel right">
	<h1> Create A Sexy Ribbit</h1>
	<%= form_for @ribbit do |f| %>
	<%= f.text_area :content, class: "ribbitText", id: "ribbitText" %>
	<%= f.submit "Ribbit!", id: "ribbitBtn" %>
	<span id="charCount">0</span>
	<% end %>

</div>

app/views/ribbits/index.html.erb
<% if current_user %>
	<%= render 'ribbits/new_form' %>
	<% end %>
	</div class="panel left">
	<h1> Public Ribbits</h1>

	<% @ribbits.each do |ribbit| %>
		<div class="ribbitWrapper">

			<a href="<%= user_path ribbit.user %>">
			<img class="avatar" src="<%= ribbit.user.avatar_url %>" />
			<span class="name"> <%= ribbit.user.name %> </span>
			</a>
			@<%= ribbit.user.username %>
			<span class="time"><%= time_ago_in_words(ribbit.created_at) %></span>
			<p> <%= ribbit.content %> </p>
			</div>
		<% end %>

		<%= javascript_include_tag 'ribbits' %>

app/views/users/buddies.html.erb
<% if current_user %>
	<%= render 'ribbits/new_form' %>
	<% end %>
	</div class="panel left">
	<h1> Buddies Ribbits</h1>

	<% @ribbits.each do |ribbit| %>
		<div class="ribbitWrapper">

			<a href="<%= user_path ribbit.user %>">
			<img class="avatar" src="<%= ribbit.user.avatar_url %>" />
			<span class="name"> <%= ribbit.user.name %> </span>
			</a>
			@<%= ribbit.user.username %>
			<span class="time"><%= time_ago_in_words(ribbit.created_at) %></span>
			<p> <%= ribbit.content %> </p>
			</div>
		<% end %>

		<%= javascript_include_tag 'ribbits' %>

app/views/users/edit.html.erb
<div class="panel left">
	<h1> Edit Sexy Profile </h1>
	<%= form_for @user do |f| %>
	<% if @user.errors.any? %>

	<ul>

	<% @user.errors.full_messages.each do |e| %>
	<li> <%= e %> </li>
	<% end %>

	</ul>
	<% end %>

	<p>Email: <%= f.text_field :email %></p>
	<p>Name: <%= f.text_field :name %></p>
	<p>Password: <%= f.password_field :password %></p>
	<p>Password Confirmation: <%= f.password_field :password_confirmation %></p>
	
	<p><%= f.submit "Update" %></p>

	<% end %>
</div>

app/views/users/index.html.erb
<% if current_user %>
	<%= render "ribbits/new_form" %>
	<% end %> 

<div class="panel left">
<h1> Public Sexy Profiles <h1>
<% @users.each do |user| %>
	<div class="ribbitWrapper">
	<a href="<%= user_path user %>">


			<img class="avatar" src="<%= user.avatar_url %>" />
			<span class="name"><%= user.name %></span> 
			</a>
			@<%= @username %>
			<p>
					<%= user.ribbits.length %> Sexy Ribbits
					<span class="spacing">  | <%= user.followers.length %> Followers </span>
					<span class="spacing">  |  <%= user.followeds.length %>  Following </span>

				</p>

			

				<% if user.ribbits.first %>
				<p> <%= user.ribbits.first.cotent %> </p>
				<% end %>
			</div>
		<% end %>
	</div>



	<%= javascript_include_tag "ribbits" %>

app/views/users/new.html.erb
<img src="/gfx/frog.jpg" />
<div class="panel right">
<h1> New to Ribbit? </h1>
<p>
	<%= form_for (User.new) do |f| %>
		<% if @user.errors.any? %>
			<ul>
			<% @user.errors.full_messages.each do |e| %>
				<li><%= e %></li>
				<% end %>
			</ul>
		<% end %>

		<%= f.text_field :email, placeholder: "sexy time email" %>
		<%= f.text_field :name, placeholder: "sexy time name" %>
		<%= f.text_field :username, placeholder: "sexy time username" %>
		<%= f.password_field :password, placeholder: "sexy time password" %>
		<%= f.password_field :password_confirmation, placeholder: "sexy time password" %>
		<%= f.submit "Create Account" %>

		<% end %>
		</p>
		</div>

app/views/users/show.html.erb
 <% if current_user %>
	<%= render 'ribbits/new_form' %>
<% end %>



<div id="ribbits" class="panel left">
	<h1> Sexy Ribbit Profile</h1>
	<%= link_to("edit profile", edit_user_path(@user)) if @user == current_user %>

	<div class="ribbitwrapper">

	<img class="avatar" src="<%= @user.avatar_url %>" />
	<span class="name"><%= @user.name %></span> @<%= @username %>
	<p>
			<%= @user.ribbits.length %> Sexy Ribbits
			<span class="spacing">  | <%= @user.followers.length %> Followers </span>
			<span class="spacing">  |  <%= @user.followeds.length %>  Following </span>



	


		<% if current_user && @user != current_user %>
			<% if current_user.following? @user %>

			<%= form_for @relationship, method: :delete do |f| %>
			<%= f.submit "Unfollow" %>
				<% end %>

			<% else %>
				<%= form_for @relationship do |f| %>
					<%= f.hidden_field :followed_id, value: @user.id %>
					<%= f.submit "Follow" %>


					<% end %>
				<% end %>
			<% end %>


		</p>
	</div>
	</div>

	<div class="panel left">
	<h1> Ribbits</h1>


	<% @user.ribbits.each do |ribbit| %>
		<div class="ribbitWrapper">
			<img class="avatar" src="<%= ribbit.user.avatar_url %>" />
			<span class="name"> <%= ribbit.user.name %> </span>
			
			@<%= ribbit.user.username %>
			<span class="time"><%= time_ago_in_words(ribbit.created_at) %></span>
			<p> <%= ribbit.content %> </p>
			</div>
		<% end %>
		</div>


<%= javascript_include_tag 'ribbits' %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>